version: "3.8"
services:
  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - jetstream
    env_file:
      - .env
    networks:
      - bun

  jetstream:
    image: "ghcr.io/juni-b-queer/jetstream-new:personal-branch"
    container_name: jetstream
    environment:
      - CURSOR_FILE=/data/cursor.json
    ports:
      - "6008:6008"
    volumes:
      - ./data:/data
    networks:
      - bun

networks:
  bun:
    driver: bridge
